[package]
name = "node-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
jsonrpc-core = "12.0.0"
jsonrpc-core-client = "12.0.0"
jsonrpc-derive = "12.0.0"
jsonrpc-pubsub = "12.0.0"
node-primitives = { package = "node-primitives", path = "../primitives" }
parity-codec = "4.1.1"
runtime_primitives = { package = "sr-primitives", path = "../../core/sr-primitives" }
serde = { version = "1.0", features = ["derive"] }
transaction_pool = { package = "substrate-transaction-pool", path = "../../core/transaction-pool" }
