[package]
name = "node-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
jsonrpc-core = "12.0.0"
jsonrpc-core-client = "12.0.0"
jsonrpc-derive = "12.0.0"
jsonrpc-pubsub = "12.0.0"
keyring = { package = "substrate-keyring", path = "../../core/keyring" }
node-primitives = { path = "../primitives" }
parity-codec = "4.1.1"
serde = { version = "1.0", features = ["derive"] }
sr-primitives = { path = "../../core/sr-primitives" }
transaction_pool = { package = "substrate-transaction-pool", path = "../../core/transaction-pool" }

[dev-dependencies]
node-executor = { path = "../executor" }
node-runtime = { path = "../runtime" }
substrate-primitives = { path = "../../core/primitives" }
test-client = { package = "substrate-test-client", path = "../../core/test-client" }
