[package]
name = "substrate-consensus-accountable-safety-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Accountable Safety"
edition = "2018"

[dependencies]
runtime-primitives = { package = "sr-primitives", path = "../../../sr-primitives", default-features = false }
rstd = { package = "sr-std", path = "../../../sr-std", default-features = false }
parity-codec = { version = "4.1.1", default-features = false, features = ["derive"] }
grandpa-primitives = { package = "finality-grandpa-primitives", path = "/home/marcio/repos/finality-grandpa/primitives", default-features = false }
substrate-primitives = { path = "../../../primitives", default-features = false }
serde = { version = "1.0", optional = true, features = ["derive"] }

[features]
default = ["std"]
std = [
	"runtime-primitives/std",
	"rstd/std",
	"parity-codec/std",
	"grandpa-primitives/std",
	"substrate-primitives/std",	
	"serde",
]