[package]
name = "substrate-consensus-accountable-safety"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Common utilities for accountable safety"
edition = "2018"

[dependencies]
client = { package = "substrate-client", path = "../../client" }
transaction_pool = { package = "substrate-transaction-pool", path = "../../transaction-pool" }
node-runtime = { path = "../../../node/runtime" }
runtime_primitives = { package = "sr-primitives", path = "../../sr-primitives" }
substrate-primitives = { path = "../../primitives" }
grandpa = { package = "finality-grandpa", path = "/home/marcio/repos/finality-grandpa", features = ["derive-codec"]}
# grandpa = { package = "finality-grandpa", git = "https://github.com/paritytech/finality-grandpa/", branch = "marcio/grandpa-primitives", features = ["derive-codec"] }
parity-codec = { version = "4.1.1", default-features = false, features = ["derive"] }
log = "0.4"
