[package]
name = "substrate-finality-grandpa"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
fork-tree = { path = "../../core/utils/fork-tree" }
futures = "0.1"
futures03 = { package = "futures-preview", version = "0.3.0-alpha.17", features = ["compat"] }
log = "0.4"
parking_lot = "0.8.0"
tokio-executor = "0.1.7"
tokio-timer = "0.2.11"
rand = "0.6"
parity-codec = { version = "4.1.1", features = ["derive"] }
runtime_primitives = { package = "sr-primitives", path = "../sr-primitives" }
consensus_common = { package = "substrate-consensus-common", path = "../consensus/common" }
substrate-primitives = { path = "../primitives" }
substrate-telemetry = { path = "../telemetry" }
serde_json = "1.0"
client = { package = "substrate-client", path = "../client" }
inherents = { package = "substrate-inherents", path = "../../core/inherents" }
network = { package = "substrate-network", path = "../network" }
service = { package = "substrate-service", path = "../service", optional = true }
srml-finality-tracker = { path = "../../srml/finality-tracker" }
srml-grandpa = { path = "../../srml/grandpa" }
fg_primitives = { package = "substrate-finality-grandpa-primitives", path = "primitives" }
# grandpa = { package = "finality-grandpa", git = "https://github.com/paritytech/finality-grandpa/", branch = "marcio/grandpa-primitives", features = ["derive-codec"] }
grandpa = { package = "finality-grandpa", path = "/home/marcio/repos/finality-grandpa", features = ["derive-codec"] }
grandpa-primitives = { package = "finality-grandpa-primitives", path = "/home/marcio/repos/finality-grandpa/primitives" }
# grandpa-primitives = { package = "finality-grandpa-primitives", git = "https://github.com/paritytech/finality-grandpa/", branch = "marcio/grandpa-primitives", path = "primitives" }
consensus_accountable_safety = { package = "substrate-consensus-accountable-safety", path = "../consensus/accountable-safety" }
consensus_accountable_safety_primitives = { package = "substrate-consensus-accountable-safety-primitives", path = "../consensus/accountable-safety/primitives" }
transaction_pool = { package = "substrate-transaction-pool", path = "../transaction-pool" }
num-traits = { version = "0.2" }

[dev-dependencies]
# consensus_common = { package = "substrate-consensus-common", path = "../consensus/common" }
# grandpa = { package = "finality-grandpa", git = "https://github.com/paritytech/finality-grandpa/", branch = "marcio/grandpa-primitives", features = ["derive-codec", "test-helpers"] }
grandpa = { package = "finality-grandpa", path = "/home/marcio/repos/finality-grandpa", features = ["derive-codec", "test-helpers"] }
network = { package = "substrate-network", path = "../network", features = ["test-helpers"] }
keyring = { package = "substrate-keyring", path = "../keyring" }
test-client = { package = "substrate-test-runtime-client", path = "../test-runtime/client"}
env_logger = "0.6"
tokio = "0.1.17"

[features]
default = ["service-integration"]
service-integration = ["service"]
