[package]
name = "substrate-consensus-aura-primitives"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Aura consensus"
edition = "2018"

[dependencies]
substrate-client = { path = "../../../client", default-features = false }
runtime_primitives = { package = "sr-primitives", path = "../../../sr-primitives", default-features = false }
rstd = { package = "sr-std", path = "../../../sr-std", default-features = false }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
	"substrate-client/std",
]
