[package]
name = "substrate-consensus-aura-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Aura consensus"
edition = "2018"

[dependencies]
parity-codec = { version = "3.5.1", default-features = false, features = ["derive"] }
substrate-client = { path = "../../../client", default-features = false }
runtime_primitives = { package = "sr-primitives", path = "../../../sr-primitives", default-features = false }
primitives = { package = "substrate-primitives", path = "../../../primitives", default-features = false }
rstd = { package = "sr-std", path = "../../../sr-std", default-features = false }
consensus = { package = "srml-consensus", path = "../../../../srml/consensus", default-features = false }
safety-primitives = { package = "substrate-consensus-safety-primitives", path = "../../safety/primitives" }

[features]
default = ["std"]
std = [
	"runtime_primitives/std",
	"substrate-client/std",
	"primitives/std",
]
