[package]
name = "substrate-consensus-aura-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Aura consensus"
edition = "2018"

[dependencies]
parity-codec = "3.4"
substrate-client = { path = "../../../client", default-features = false }
runtime_primitives = { package = "sr-primitives", path = "../../../sr-primitives", default-features = false }
consensus_common = { package = "substrate-consensus-common", path = "../../common" }
primitives = { package = "substrate-primitives", path = "../../../primitives" }

[features]
default = ["std"]
std = [
	"runtime_primitives/std",
	"substrate-client/std",
]
